// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP6zvGcHFd7_CsPcPeAoVT4bg-Ok2tlDk',
    appId: '1:124116458043:web:f7675b199e7f5e6278da1e',
    messagingSenderId: '124116458043',
    projectId: 'breaking-the-habit-1f579',
    authDomain: 'breaking-the-habit-1f579.firebaseapp.com',
    storageBucket: 'breaking-the-habit-1f579.appspot.com',
    measurementId: 'G-8MF002NW7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6RaQ0pWx5h5Ag7SdPd7oZyaA7mWcjk5k',
    appId: '1:124116458043:android:c03c04680a1638c178da1e',
    messagingSenderId: '124116458043',
    projectId: 'breaking-the-habit-1f579',
    storageBucket: 'breaking-the-habit-1f579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVr4eHyZE82RbTbIHg7YjGRYJ96mp01sk',
    appId: '1:124116458043:ios:82a9c26a0b0dd29378da1e',
    messagingSenderId: '124116458043',
    projectId: 'breaking-the-habit-1f579',
    storageBucket: 'breaking-the-habit-1f579.appspot.com',
    iosClientId: '124116458043-9f0hj7clupfoonr4skd83c7kuvkhbrdr.apps.googleusercontent.com',
    iosBundleId: 'tk.vorky.bth',
  );
}
